[package]
name = "ulid-rs"
version = "0.1.0"
authors = ["Suyash <hi@suy.io>"]
edition = "2018"

[dependencies]
thiserror = "1.0.20"

[dev-dependencies]
chrono = "0.4.13"
rand = "0.7.3"
criterion = "0.3.3"

[[bench]]
name = "benches"
harness = false
